name 'bkg-django'
version '0.4.4'
source 'https://github.com/bkg/puppet-django.git'
author 'Brian Galey'
license 'Apache License, Version 2.0'
summary 'Django application stack'
project_page 'https://github.com/bkg/puppet-django.git'

dependency 'puppetlabs/apt', '1.x.x'
dependency 'puppetlabs/postgresql', '>= 3.0.0'
dependency 'stankevich/python', '1.2.x'
dependency 'jfryman/nginx', '0.2.x'
